name: Report a problem
description: Something broken? Report it here.
body:
  - type: markdown
    attributes:
      value: |
        Important to note that your issue may have already been reported before. Please check the
        [issue board](https://github.com/sr229/kuru-kuru/issues) if you haven't already.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug description
      description: How did you find the bug? Any additional details that might help?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots or videos
      description: Add screenshots or videos that show the bug here.
      placeholder: Drag and drop the screenshots/videos into this box.
    validations:
      required: false